AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  SEOO:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 256
      Timeout: 899
      Role: 'arn:aws:iam::634156574820:role/service-role/SEOO-role-6h2duglg'
      Layers:
        - 'arn:aws:lambda:ap-south-1:634156574820:layer:spacy1:1'
        - 'arn:aws:lambda:ap-south-1:634156574820:layer:spacy2:1'
